[package]
name = "sxlang"
version = "0.1.0"
authors = ["Maitre Van Diest", "Delthas", "Emersion"]

[dependencies]
clap = "2.25.0"
env_logger = "0.4.3"
log = "0.3.8"
regex = "0.2"

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
